packages:
  - packages/*
  - docs
  - tests
  - bundle-analyzer

catalog:
  '@sveltejs/kit': 2.59.1
  '@vitest/browser': ^4.1.6
  '@sveltejs/vite-plugin-svelte': ^7.1.2
  '@tailwindcss/vite': ^4.3.0
  '@types/node': ^25.7.0
  playwright: 1.60.0
  runed: ^0.37.1
  svelte: 5.55.4
  svelte-check: ^4.4.8
  tailwindcss: ^4.3.0
  typescript: ^6.0.3
  vite: ^8.0.12
  vitest: ^4.1.6
  vitest-browser-svelte: ^2.1.1
