<!-- eslint-disable svelte/no-at-html-tags -->
{@html `<figure data-rehype-pretty-code-figure=""><pre class="relative mb-4 mt-6 overflow-x-auto rounded-card border-2 border-muted py-8 Serendipity Midnight Serendipity Morning" tabindex="0" data-language="js" data-theme="Serendipity Midnight Serendipity Morning">	<!----><!--1sunpjx--><code data-language="js" data-theme="Serendipity Midnight Serendipity Morning" style="display: grid;"><span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">import </span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">typography</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383"> from </span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">"@tailwindcss/typography"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">import </span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">animate</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383"> from </span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">"tailwindcss-animate"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">import </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">{</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040"> fontFamily</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> }</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383"> from </span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">"tailwindcss/defaultTheme"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
	<span data-line=""> </span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">/**</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> @</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">type</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">import('tailwindcss').Config</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">}</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> */</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">export default </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">{</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">	darkMode</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "class"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">	content</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040"> [</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">"./src/**/*.{html,js,svelte,ts}"</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">]</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">	theme</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">		container</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">			center</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> true</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">			screens</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">				"2xl"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "1440px"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">			},</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">		},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">		extend</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">			colors</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				border</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">					DEFAULT</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "hsl(var(--border-card))"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">					input</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "hsl(var(--border-input))"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">					"input-hover"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "hsl(var(--border-input-hover))"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">				},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				background</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">					DEFAULT</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "hsl(var(--background) / &lt;alpha-value&gt;)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">					alt</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "hsl(var(--background-alt) / &lt;alpha-value&gt;)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">				},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				foreground</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">					DEFAULT</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "hsl(var(--foreground) / &lt;alpha-value&gt;)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">					alt</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "hsl(var(--foreground-alt) / &lt;alpha-value&gt;)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">				},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				muted</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">					DEFAULT</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "hsl(var(--muted) / &lt;alpha-value&gt;)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">					foreground</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "hsl(var(--muted-foreground))"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">				},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				dark</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">					DEFAULT</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "hsl(var(--dark) / &lt;alpha-value&gt;)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">					4</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "hsl(var(--dark-04))"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">					10</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "hsl(var(--dark-10))"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">					40</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "hsl(var(--dark-40))"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">				},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				accent</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">					DEFAULT</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "hsl(var(--accent) / &lt;alpha-value&gt;)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">					foreground</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "hsl(var(--accent-foreground) / &lt;alpha-value&gt;)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">				},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				destructive</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">					DEFAULT</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "hsl(var(--destructive) / &lt;alpha-value&gt;)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">				},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				contrast</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">					DEFAULT</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "hsl(var(--contrast) / &lt;alpha-value&gt;)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">				},</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">			},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">			fontFamily</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				sans</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040"> [</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">"Inter"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383"> ...</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">fontFamily</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">.</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">sans]</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				mono</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040"> [</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">"Source Code Pro"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383"> ...</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">fontFamily</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">.</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">mono]</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				alt</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040"> [</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">"Courier"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383"> ...</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">fontFamily</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">.</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">sans]</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">			},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">			fontSize</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				xxs</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "10px"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">			},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">			borderWidth</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">				6</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "6px"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">			},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">			borderRadius</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				card</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "16px"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">				"card-lg"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "20px"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">				"card-sm"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "10px"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				input</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "9px"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				button</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "5px"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">				"5px"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "5px"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">				"9px"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "9px"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">				"10px"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "10px"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">				"15px"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "15px"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">			},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">			height</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				input</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "3rem"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">				"input-sm"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "2.5rem"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">			},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">			boxShadow</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				mini</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "var(--shadow-mini)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">				"mini-inset"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "var(--shadow-mini-inset)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				popover</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "var(--shadow-popover)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				kbd</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "var(--shadow-kbd)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				btn</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "var(--shadow-btn)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				card</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "var(--shadow-card)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">				"date-field-focus"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "var(--shadow-date-field-focus)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">			},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">			opacity</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">				8</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "0.08"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">			},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">			scale</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">				80</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> ".80"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">				98</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> ".98"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">				99</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> ".99"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">			},</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">		},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">		keyframes</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">			"accordion-down"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				from</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383"> height</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "0"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> },</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				to</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383"> height</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "var(--bits-accordion-content-height)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> },</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">			},</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">			"accordion-up"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				from</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383"> height</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "var(--bits-accordion-content-height)"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> },</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">				to</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383"> height</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "0"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> },</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">			},</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">			"caret-blink"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">				"0%,70%,100%"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383"> opacity</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "1"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> },</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">				"20%,50%"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383"> opacity</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "0"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> },</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">			},</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">		},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">		animation</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">			"accordion-down"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "accordion-down 0.2s ease-out"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">			"accordion-up"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "accordion-up 0.2s ease-out"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">			"caret-blink"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> "caret-blink 1.25s ease-out infinite"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">		},</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	},</span></span>
	<span data-line=""><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">	plugins</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040"> [typography</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040"> animate]</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
	<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">};</span></span></code>
	</pre></figure>`}
