import type * as I from "./_types.js";
import type {
	ArrowProps,
	CheckboxIndicatorProps,
	CheckboxItemEvents,
	CheckboxItemProps,
	ContentEvents,
	GroupProps,
	ItemEvents,
	ItemProps,
	LabelProps,
	Props,
	RadioGroupProps,
	RadioIndicatorProps,
	RadioItemEvents,
	RadioItemProps,
	SeparatorProps,
	SubContentEvents,
	SubContentProps,
	SubProps,
	SubTriggerEvents,
	SubTriggerProps,
	ContextTriggerEvents as TriggerEvents,
	ContextTriggerProps as TriggerProps,
} from "$lib/bits/menu/index.js";
import type { HTMLDivAttributes, Transition } from "$lib/internal/index.js";

type ContentProps<
	T extends Transition = Transition,
	In extends Transition = Transition,
	Out extends Transition = Transition,
> = I.ContentProps<T, In, Out> & HTMLDivAttributes;

export type {
	Props,
	SubProps,
	ItemProps,
	ArrowProps,
	GroupProps,
	LabelProps,
	ContentProps,
	TriggerProps,
	RadioItemProps,
	SeparatorProps,
	RadioGroupProps,
	SubContentProps,
	SubTriggerProps,
	CheckboxItemProps,
	CheckboxIndicatorProps,
	RadioIndicatorProps,
	//,
	ItemEvents,
	TriggerEvents,
	ContentEvents,
	RadioItemEvents,
	SubContentEvents,
	SubTriggerEvents,
	CheckboxItemEvents,
};
