/**
 * Creates a unique ID for a given uid and optional prefix.
 *
 * @param uid - the uid generated by $props.id()
 * @param prefix - optional prefix to use for the id (defaults to "bits")
 */
export function createId(uid: string): string;
export function createId(prefix: string, uid: string): string;
export function createId(prefixOrUid: string, uid?: string): string {
	if (uid === undefined) return `bits-${prefixOrUid}`;
	return `bits-${prefixOrUid}-${uid}`;
}
