<!-- eslint-disable-next-line svelte/no-at-html-tags -->
{@html `<figure data-rehype-pretty-code-figure=""><pre class="relative mb-4 mt-6 overflow-x-auto rounded-card border-2 border-muted py-8 Serendipity Midnight Serendipity Morning" tabindex="0" data-language="css" data-theme="Serendipity Midnight Serendipity Morning">	<!----><!--19xvx1e--><code data-language="css" data-theme="Serendipity Midnight Serendipity Morning" style="display: grid;"><span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">@</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">import</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> url</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">"https://fonts.googleapis.com/css2?family=Source+Code+Pro:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&amp;display=swap"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">);</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">@</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">import</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> url</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">"https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&amp;display=swap"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">);</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">@</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">tailwind</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040"> base</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">@</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">tailwind</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040"> components</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">@</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">tailwind</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040"> utilities</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">@</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">layer</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040"> base </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">{</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	:</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">root</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">		/*</span><span style="--shiki-dark:#707070;--shiki-light:#9A9A9A"> Colors </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">*/</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--background</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 100</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--background-alt</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 100</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--foreground</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 9</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--foreground-alt</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 32</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--muted</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 240</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 5</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 96</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--muted-foreground</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 9</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> / </span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0.4</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--border</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 240</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 6</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 10</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--border-input</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 240</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 6</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 10</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> / </span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0.17</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--border-input-hover</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 240</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 6</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 10</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> / </span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0.4</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--border-card</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 240</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 6</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 10</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> / </span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0.1</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--dark</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 240</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 6</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 10</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--dark-10</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 240</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 6</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 10</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> / </span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0.1</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--dark-40</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 240</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 6</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 10</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> / </span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0.4</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--dark-04</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 240</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 6</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 10</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> / </span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0.04</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--accent</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 204</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 94</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 94</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--accent-foreground</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 204</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 80</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 16</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--destructive</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 347</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 77</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 50</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">		/*</span><span style="--shiki-dark:#707070;--shiki-light:#9A9A9A"> black </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">*/</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--constrast</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">		/*</span><span style="--shiki-dark:#707070;--shiki-light:#9A9A9A"> Shadows </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">*/</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--shadow-mini</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 1</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 1</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> rgba</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0.04</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">);</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--shadow-mini-inset</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 1</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> rgba</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0.04</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">)</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> inset</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--shadow-popover</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 7</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 12</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 3</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> hsla</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D">var</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">--dark-10</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">));</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--shadow-kbd</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 2</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> rgba</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0.07</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">);</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--shadow-btn</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 1</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 1</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> rgba</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0.03</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">);</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--shadow-card</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 2</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 1</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> rgba</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0.04</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">);</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--shadow-date-field-focus</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 3</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> rgba</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">24</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 24</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 27</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0.17</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">);</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	.</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">dark</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">		/*</span><span style="--shiki-dark:#707070;--shiki-light:#9A9A9A"> Colors </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">*/</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--background</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 5</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--background-alt</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 8</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--foreground</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 95</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--foreground-alt</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 70</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--muted</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 240</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 4</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 16</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--muted-foreground</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 100</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> / </span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0.4</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--border</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 96</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--border-input</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 96</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> / </span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0.17</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--border-input-hover</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 96</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> / </span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0.4</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--border-card</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 96</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> / </span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0.1</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--dark</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 96</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--dark-40</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 96</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> / </span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0.4</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--dark-10</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 96</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> / </span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0.1</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--dark-04</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 96</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> / </span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0.04</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--accent</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 204</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 90</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 90</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--accent-foreground</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 204</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 94</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 94</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--destructive</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 350</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 89</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 60</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">		/*</span><span style="--shiki-dark:#707070;--shiki-light:#9A9A9A"> white </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">*/</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--constrast</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 100</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">		/*</span><span style="--shiki-dark:#707070;--shiki-light:#9A9A9A"> Shadows </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">*/</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--shadow-mini</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 1</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 1</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> rgba</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0.3</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">);</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--shadow-mini-inset</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 1</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> rgba</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0.5</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">)</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> inset</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--shadow-popover</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 7</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 12</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 3</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> hsla</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">deg</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> / </span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">30</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">);</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--shadow-kbd</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 2</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> rgba</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">255</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 255</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 255</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0.07</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">);</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--shadow-btn</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 1</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 1</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> rgba</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0.2</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">);</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--shadow-card</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 2</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 1</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> rgba</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0.4</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">);</span></span>
<span data-line=""><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">		--shadow-date-field-focus</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 3</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">px</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> rgba</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">244</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 244</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 245</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0.1</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">);</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">}</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">@</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">layer</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040"> base </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">{</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">	*</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">		@</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">apply</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> border-border</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">	html</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">		-webkit-text-size-adjust</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 100</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">%</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">		font-variation-settings</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> normal</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">	body</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">		@</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">apply</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> bg-background</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> text-foreground</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">		font-feature-settings</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span></span>
<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">			"rlig"</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 1</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">			"calt"</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 1</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	/*</span><span style="--shiki-dark:#707070;--shiki-light:#9A9A9A"> Mobile tap highlight </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">*/</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	/*</span><span style="--shiki-dark:#707070;--shiki-light:#9A9A9A"> https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-tap-highlight-color </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">*/</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">	html</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">		-webkit-tap-highlight-color</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> rgba</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">128</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 128</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 128</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0.5</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">);</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	::</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">selection</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">		background</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> #</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">fdffa4</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">		color</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> black</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	/*</span><span style="--shiki-dark:#707070;--shiki-light:#9A9A9A"> === Scrollbars === </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">*/</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	::</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">-webkit-scrollbar</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">		@</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">apply</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> w-</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">2</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">		@</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">apply</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> h-</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">2</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	::</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">-webkit-scrollbar-track</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">		@</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">apply</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040"> !</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">bg-transparent</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	::</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">-webkit-scrollbar-thumb</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">		@</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">apply</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> rounded-card-lg</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040"> !</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">bg-dark-</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">10</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	::</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">-webkit-scrollbar-corner</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">		background</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> rgba</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">);</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	/*</span><span style="--shiki-dark:#707070;--shiki-light:#9A9A9A"> Firefox </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">*/</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	/*</span><span style="--shiki-dark:#707070;--shiki-light:#9A9A9A"> https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color#browser_compatibility </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">*/</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">	html</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">		scrollbar-color</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> var</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">--bg-muted</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">);</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	.</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">antialised</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">		-webkit-font-smoothing</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> antialiased</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">		-moz-osx-font-smoothing</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> grayscale</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">}</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">@</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">layer</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040"> utilities </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">{</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	.</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">step</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">		counter-increment</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> step</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	.</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">step</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">before</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">		@</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">apply</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> absolute</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> inline-flex</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> h-</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">9 </span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">w-</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">9 </span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">items-center</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> justify-center</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> rounded-full</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> border-</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">4 </span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">border-background</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> bg-muted</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> text-center</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> -indent-px</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> font-mono</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> text-base</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> font-medium</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">		@</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">apply</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> ml-</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">[</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">-</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">50</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">px</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">] </span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">mt-</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">[</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">-</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">4</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">px</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">]</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">		content</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EE8679;--shiki-light:#D26A5D"> counter</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">step</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">);</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">}</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">@</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">layer</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040"> components </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">{</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">	*</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">not</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">body</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">):</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">not</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">(.</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">focus-override</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">)</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">		outline</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> none </span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">!important</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">		&amp;</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">focus-visible {</span></span>
<span data-line=""><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">			@apply focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-foreground focus-visible:ring-offset-2 focus-visible:ring-offset-background</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">		}</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	.</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">link</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">		@</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">apply</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> inline-flex</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> items-center</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> gap-</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">1 </span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">rounded-sm</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> font-medium</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> underline</span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C"> underline-offset-</span><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">4 </span><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">hover</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">text-foreground/</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E">80</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-foreground focus-visible:ring-offset-2 focus-visible:ring-offset-background</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">	input</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">::</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">-webkit-outer-spin-button</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">,</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">	input</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">::</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">-webkit-inner-spin-button</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">		-webkit-appearance</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> none</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">		margin</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#EEEEEE;--shiki-light:#4E4E4E"> 0</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""> </span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	/*</span><span style="--shiki-dark:#707070;--shiki-light:#9A9A9A"> Firefox </span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">*/</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">	input</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">[</span><span style="--shiki-dark:#B0E2FD;--shiki-light:#858585">type</span><span style="--shiki-dark:#5BA2D0;--shiki-light:#838383">=</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C">"number"</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">]</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A"> {</span></span>
<span data-line=""><span style="--shiki-dark:#E6E6E6;--shiki-light:#4C4C4C">		-moz-appearance</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">:</span><span style="--shiki-dark:#E3D891;--shiki-light:#4C4C4C"> textfield</span><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">;</span></span>
<span data-line=""><span style="--shiki-dark:#8D8F9E;--shiki-light:#9A9A9A">	}</span></span>
<span data-line=""><span style="--shiki-dark:#DEE0EF;--shiki-light:#404040">}</span></span></code>
</pre></figure>`}
