/**
 * Creates a unique ID for a given prefix and uid.
 *
 * @param prefix - prefix to use for the id
 * @param uid - the uid generated by $props.id()
 */
export function createId(prefix: string, uid: string) {
	return `${prefix}-${uid}`;
}
