name: Bundle Analysis

on:
    pull_request:
        paths:
            - packages/bits-ui/**
            - bundle-analyzer/**
        types: [opened, synchronize, reopened]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number }}
    cancel-in-progress: true

jobs:
    bundle-analysis:
        name: Bundle Size Analysis
        runs-on: ubuntu-latest
        if: github.event.pull_request.draft == false

        permissions:
            contents: read
            pull-requests: write

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Build packages
              run: pnpm build:packages

            - name: Run bundle analysis
              run: pnpm bundle:analyze

            - name: Save PR bundle report
              run: |
                  mkdir -p ./bundle-analysis-temp
                  cp ./bundle-analyzer/bundle-reports/latest.json ./bundle-analysis-temp/pr-report.json

            - name: Checkout target branch
              run: |
                  git fetch origin ${{ github.base_ref }}
                  git checkout origin/${{ github.base_ref }}

            - name: Install dependencies (target branch)
              run: pnpm install --frozen-lockfile

            - name: Build packages (target branch)
              run: pnpm build:packages

            - name: Run bundle analysis (target branch)
              run: pnpm bundle:analyze
              continue-on-error: true

            - name: Save target branch bundle report
              run: |
                  if [ -f "./bundle-analyzer/bundle-reports/latest.json" ]; then
                      cp ./bundle-analyzer/bundle-reports/latest.json ./bundle-analysis-temp/target-report.json
                  else
                      echo '{"timestamp":"","results":[]}' > ./bundle-analysis-temp/target-report.json
                  fi

            - name: Checkout PR again
              run: git checkout ${{ github.head_ref }}

            - name: Generate bundle comparison comment
              id: bundle-comment
              run: |
                  node ./bundle-analyzer/generate-pr-comment.js \
                    ./bundle-analysis-temp/pr-report.json \
                    ./bundle-analysis-temp/target-report.json

            - name: Find existing comment
              uses: peter-evans/find-comment@915d841dae6a4f191bb78faf61a257411d7be4d2
              id: existing-comment
              with:
                  issue-number: ${{ github.event.pull_request.number }}
                  comment-author: "github-actions[bot]"
                  body-includes: "## 📦 Bundle Size Analysis"

            - name: Update or create comment
              uses: peter-evans/create-or-update-comment@be17e0c03de886b7aff3fb3224d28bfb6fc5d114
              with:
                  comment-id: ${{ steps.existing-comment.outputs.comment-id }}
                  issue-number: ${{ github.event.pull_request.number }}
                  body-path: ./bundle-analysis-temp/comment.md
                  edit-mode: replace
