name: Bundle Size Analysis

on:
    pull_request:
        branches: [main]
        paths:
            - "packages/bits-ui/**"
            - "pnpm-lock.yaml"

jobs:
    bundle-size:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            pull-requests: write

        steps:
            - name: Checkout PR
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup pnpm
              uses: pnpm/action-setup@v2

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Build packages
              run: pnpm build:packages

            - name: Generate current bundle report
              run: pnpm bundle:analyze

            - name: Save current report
              run: cp bundle-reports/latest.json bundle-reports/pr.json

            - name: Checkout main branch
              run: |
                  git fetch origin main:main
                  git checkout main

            - name: Install dependencies (main)
              run: pnpm install

            - name: Build packages (main)
              run: pnpm build:packages

            - name: Generate main branch bundle report
              run: pnpm bundle:analyze

            - name: Save main report
              run: cp bundle-reports/latest.json bundle-reports/main.json

            - name: Switch back to PR
              run: git checkout -

            - name: Compare bundle sizes
              id: compare
              run: |
                  echo "COMPARISON<<EOF" >> $GITHUB_OUTPUT
                  pnpm bundle:compare bundle-reports/pr.json bundle-reports/main.json >> $GITHUB_OUTPUT
                  echo "EOF" >> $GITHUB_OUTPUT

            - name: Comment PR
              uses: actions/github-script@v7
              with:
                  script: |
                      const comparison = `${{ steps.compare.outputs.COMPARISON }}`;

                      const body = `## 📦 Bundle Size Report

                      \`\`\`
                      ${comparison}
                      \`\`\`

                      <details>
                      <summary>ℹ️ What is this?</summary>

                      This report shows the impact of your changes on the bundle size of Bits UI components.

                      - 📈 = Size increased
                      - 📉 = Size decreased
                      - ➡️ = No significant change
                      - ✨ = New component
                      - ❌ = Component removed

                      Bundle sizes include all component exports and their dependencies.
                      </details>`;

                      // Find existing comment
                      const { data: comments } = await github.rest.issues.listComments({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.issue.number,
                      });

                      const existingComment = comments.find(comment =>
                        comment.user.type === 'Bot' && comment.body.includes('Bundle Size Report')
                      );

                      if (existingComment) {
                        // Update existing comment
                        await github.rest.issues.updateComment({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          comment_id: existingComment.id,
                          body: body
                        });
                      } else {
                        // Create new comment
                        await github.rest.issues.createComment({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          issue_number: context.issue.number,
                          body: body
                        });
                      }

            - name: Upload bundle reports
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: bundle-reports
                  path: bundle-reports/
                  retention-days: 30

