name: CI Alt

on:
    push:
        branches:
            - main
            - next
        paths-ignore:
            - ".changeset/**"
            - README.md
            - ".vscode/**"
            - CHANGELOG.md
    pull_request:
        paths-ignore:
            - ".changeset/**"
            - README.md
            - ".vscode/**"
            - CHANGELOG.md

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
    cancel-in-progress: true

jobs:
    Quality:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm
            - run: pnpm install --frozen-lockfile --prefer-offline

            - name: "Svelte Check"
              run: pnpm check

            - name: "Lint"
              run: pnpm lint

            - name: "Test"
              run: pnpm test
