name: CI

on:
    push:
        branches:
            - main
        paths-ignore:
            - ".changeset/**"
            - README.md
            - ".vscode/**"
            - CHANGELOG.md
    pull_request:
        paths-ignore:
            - ".changeset/**"
            - README.md
            - ".vscode/**"
            - CHANGELOG.md

concurrency:
    group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
    cancel-in-progress: true

jobs:
    quality:
        name: ${{ matrix.task_name }}
        runs-on: macos-latest

        strategy:
            matrix:
                task:
                    - { name: "Svelte Check", cmd: "pnpm check" }
                    - { name: "Lint", cmd: "pnpm lint" }
                    - { name: "Test", cmd: "pnpm build:packages && pnpm test" }
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            - run: pnpm install --frozen-lockfile --prefer-offline

            - name: Run ${{ matrix.task.name }}
              run: ${{ matrix.task.cmd }}
